name: Keep alive
on:
  schedule:
    - cron: "0 0 * * *"
    
jobs:
  keepalive:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - run: |
          if [[ $(git log --format="%H" --since "50 days" | head -c1 | wc -c) == 0 ]]; then
            git config user.email "typescriptbot@microsoft.com"
            git config user.name "TypeScript Bot"
            git commit --allow-empty -m "Automated commit to keep GitHub Actions active"
            git push
          fi
